server:
  port: 8211

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.57.29.205:3306/itms-acl?characterEncoding=utf-8&useSSL=false
    username: root
    password: DavidLiu7
  redis:
    host: 123.57.29.205
    port: 6379
    database: 0
    timeout: 1800000
    password: DavidLiu7
    lettuce:
      pool:
        max-active: 20 #最大连接数
        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
        max-idle: 5    #最大空闲
        min-idle: 0     #最小空闲
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
sa-token:
  # jwt秘钥
  jwt-secret-key: neud-itms
