server:
  port: 8206

mybatis-plus:
  type-enums-package: cn.neud.itms.enums
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.57.29.205:3306/itms-user?characterEncoding=utf-8&useSSL=false
    username: root
    password: DavidLiu7

  redis:
    host: 123.57.29.205
    port: 6379
    database: 0
    timeout: 1800000
    password:
    lettuce:
      pool:
        max-active: 20 #最大连接数
        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
        max-idle: 5    #最大空闲
        min-idle: 0     #最小空闲

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
wx:
  open:
    # 小程序微信appId
    # 小程序微信公众平台appId
    app_id: wxcc651fcbab275e33
    # 小程序微信公众平台api秘钥
    app_secret: 5f353399a2eae7ff6ceda383e924c5f6