spring:
  application:
    name: service-gateway
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 123.57.29.205:8848
        namespace: david-dev
        group: itms-project