server:
  port: 8203

mybatis-plus:
  type-enums-package: cn.neud.itms.enums
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.57.29.205:3306/itms-product?characterEncoding=utf-8&useSSL=false
    username: root
    password: DavidLiu7
  rabbitmq:
    host: 123.57.29.205
    port: 5672
    username: david
    password: DavidLiu7
    virtual-host: /
    publisher-confirm-type: CORRELATED  #发布确认模式，消息是否被成功发送到交换机
    publisher-returns: true
    listener:
      simple:
        prefetch: 1
        concurrency: 3
        acknowledge-mode: manual   #消费端手动确认
  redis:
    host: 123.57.29.205
    port: 6379
    database: 0
    timeout: 1800000
    password: DavidLiu7
    lettuce:
      pool:
        max-active: 20 #最大连接数
        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
        max-idle: 5    #最大空闲
        min-idle: 0     #最小空闲
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
aliyun:
  endpoint: oss-cn-beijing.aliyuncs.com
  keyid: LTAI5tRMey4xFpTjjh48fhro
  keysecret: yN7UnT6zeSxnb4EgjemvCsi4gQerZq
  bucketname: itms-bucket