server:
  port: 8210
mybatis-plus:
  type-enums-package: cn.neud.itms.enums
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
feign:
  sentinel:
    enabled: true
  client:
    config:
      default: #配置全局的feign的调用超时时间  如果 有指定的服务配置 默认的配置不会生效
        connectTimeout: 30000 # 指定的是 消费者 连接服务提供者的连接超时时间 是否能连接  单位是毫秒
        readTimeout: 50000  # 指定的是调用服务提供者的 服务 的超时时间（）  单位是毫秒
spring:
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  rabbitmq:
    host: 123.57.29.205
    port: 5672
    username: david
    password: DavidLiu7
    virtual-host: /
    publisher-confirm-type: CORRELATED
    publisher-returns: true
    listener:
      simple:
        prefetch: 1
        concurrency: 3
        acknowledge-mode: manual
  redis:
    host: 123.57.29.205
    port: 6379
    database: 0
    timeout: 1800000
    password: DavidLiu7
    lettuce:
      pool:
        max-active: 20 #最大连接数
        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
        max-idle: 5    #最大空闲
        min-idle: 0     #最小空闲
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.57.29.205:3306/itms-order?characterEncoding=utf-8&useSSL=false
    username: root
    password: DavidLiu7
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000
      idle-timeout: 500000
      max-lifetime: 540000
      maximum-pool-size: 5
      minimum-idle: 3
      pool-name: NeuHikariPool
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
# 微信
weixin:
  #小程序微信公众平台appId
  appid: wxcc651fcbab275e33
  partner: 1481962542
  partnerkey: MXb72b9RfshXZD4FRGV5KLqmv5bx9LT9
  notifyurl: http://gmall-prod.neud.cn/api/payment/weixin/notify
  cert: C:\data\apiclient_cert.p12